# Generated by Django 2.2.4 on 2019-10-28 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0016_auto_20191023_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Назва показника')),
            ],
            options={
                'verbose_name': 'Показник ефективності',
                'verbose_name_plural': 'Показники ефективності',
            },
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Employee', verbose_name='Працівник')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.KpiName', verbose_name='Показник')),
            ],
            options={
                'verbose_name': 'КПЕ',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Бонус, грн.')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Employee', verbose_name='Працівник')),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонуси',
                'ordering': ['-created'],
            },
        ),
    ]
