# Generated by Django 2.2.10 on 2020-05-05 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-period'], 'verbose_name': 'Бонус', 'verbose_name_plural': 'Бонуси'},
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['-period'], 'verbose_name': 'КПЕ'},
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='created',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='modified',
        ),
        migrations.AddField(
            model_name='bonus',
            name='period',
            field=models.DateField(default=datetime.date.today, verbose_name='Період розрахунку'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='period',
            field=models.DateField(default=datetime.date.today, verbose_name='Період розрахунку'),
        ),
    ]
