# Generated by Django 2.2.20 on 2022-01-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('html_templates', '0001_initial'),
        ('analytics', '0007_auto_20200519_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва звіту')),
                ('context', models.CharField(choices=[('receivables_context', 'Дебіторська заборгованість'), ('waiting_for_act_context', 'Чекають закриття актів'), ('payment_queue_context', 'Черга оплат'), ('overdue_payment_context', 'Протермінована опата'), ('overdue_execution_context', 'Протеріноване виконання')], max_length=50, verbose_name='Метод контексту')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='html_templates.HTMLTemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Звіт',
                'verbose_name_plural': 'Звіти',
            },
        ),
    ]
