# Generated by Django 2.2.27 on 2022-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='context',
            field=models.CharField(choices=[('receivables_context', 'Дебіторська заборгованість'), ('waiting_for_act_context', 'Чекають закриття актів'), ('payment_queue_context', 'Черга оплат'), ('overdue_payment_context', 'Протермінована опата'), ('overdue_execution_context', 'Протеріноване виконання'), ('act_list_context', 'Акти виконаних робіт'), ('payment_list_context', 'Оплати'), ('customer_report_context', 'Звіт по замовнику')], max_length=50, verbose_name='Метод контексту'),
        ),
    ]
