# Generated by Django 2.2.28 on 2022-11-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('html_templates', '0002_auto_20221117_1244'),
        ('analytics', '0009_auto_20220708_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва')),
                ('yAxis', models.CharField(max_length=50, verbose_name='Вісь Y')),
                ('context', models.CharField(choices=[('income_context', 'Фінансова аналітика'), ('customer_income_context', 'Фінансова аналітика по замовнику'), ('income_structure_context', 'Структура доходів')], max_length=50, verbose_name='Метод контексту')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='html_templates.HTMLTemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Діаграма',
                'verbose_name_plural': 'Діаграми',
            },
        ),
    ]
