# Generated by Django 2.2.28 on 2022-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='context',
            field=models.CharField(choices=[('fin_analysis_context', 'Фінансова аналітика'), ('customer_fin_analysis_context', 'Фінансова аналітика по замовнику'), ('income_structure_context', 'Структура доходів'), ('receivables_structure_context', 'Структура дебіторки')], max_length=50, verbose_name='Метод контексту'),
        ),
    ]
