# Generated by Django 2.2.28 on 2022-11-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_auto_20221118_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='context',
            field=models.CharField(choices=[('fin_analysis_context', 'Фінансова аналітика'), ('customer_fin_analysis_context', 'Фінансова аналітика по замовнику'), ('income_structure_context', 'Структура доходів')], max_length=50, verbose_name='Метод контексту'),
        ),
    ]
