# Generated by Django 3.2.18 on 2023-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_auto_20221120_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='name',
            field=models.CharField(choices=[('BI', 'Бонус Ітел-Cервіс'), ('BG', 'Бонус Галкомпроект'), ('BS', 'Бонус ФОП'), ('TA', 'Бонуси Загальні'), ('PR', 'Продуктивність')], default='BI', max_length=2, verbose_name='Показник ефективності'),
        ),
    ]
