# Generated by Django 3.2.18 on 2023-04-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_auto_20230407_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='context',
            field=models.CharField(choices=[('fin_analysis_context', 'Фінансова аналітика'), ('customer_fin_analysis_context', 'Фінансова аналітика по замовнику'), ('income_structure_context', 'Структура доходів'), ('employee_productivity_context', 'Продуктивність працівників'), ('manager_productivity_context', 'Ефективність менеджерів')], max_length=50, verbose_name='Метод контексту'),
        ),
    ]
