# Generated by Django 2.2.20 on 2021-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва шаблону')),
                ('document_type', models.CharField(choices=[('IN', 'Рахунок'), ('DE', 'Договір'), ('AC', 'Акт'), ('RE', 'Звіт')], default='DE', max_length=2, verbose_name='Тип документу')),
                ('html_template', models.TextField(verbose_name='Шаблон HTML')),
                ('html_context', models.CharField(blank=True, max_length=255, verbose_name='Контекст шаблону')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблони',
                'ordering': ['name'],
            },
        ),
    ]
