# Generated by Django 2.2.28 on 2022-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltemplate',
            name='document_type',
            field=models.CharField(choices=[('IN', 'Рахунок'), ('DE', 'Договір'), ('AC', 'Акт'), ('RE', 'Звіт'), ('CH', 'Діаграма')], default='DE', max_length=2, verbose_name='Тип документу'),
        ),
    ]
