# Generated by Django 2.2.20 on 2021-11-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_holiday',
            field=models.BooleanField(default=False, verbose_name='Вихідний день'),
        ),
    ]
