# Generated by Django 2.0 on 2018-02-12 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import planner.formatChecker
import planner.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквізити')),
            ],
            options={
                'verbose_name': 'Компанія',
                'verbose_name_plural': 'Компанії',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Контактна особа')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквізити')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Підрярник',
                'verbose_name_plural': 'Підрядники',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Контактна особа')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('requisites', models.TextField(blank=True, verbose_name='Реквізити')),
                ('debtor_term', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Термін післяоплати')),
            ],
            options={
                'verbose_name': 'Замовник',
                'verbose_name_plural': 'Замовники',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер договору')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Вартість робіт, грн.')),
                ('value_correction', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Коригування вартості робіт, грн.')),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Аванс, грн.')),
                ('pay_status', models.CharField(choices=[('NP', 'Не оплачений'), ('AP', 'Оплачений аванс'), ('PU', 'Оплачений')], default='NP', max_length=2, verbose_name='Статус оплати')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Дата оплати')),
                ('expire_date', models.DateField(verbose_name='Дата закінчення договору')),
                ('act_status', models.CharField(choices=[('NI', 'Не виписаний'), ('PI', 'Виписаний частково'), ('IS', 'Виписаний')], default='NI', max_length=2, verbose_name='Акт виконаних робіт')),
                ('act_date', models.DateField(blank=True, null=True, verbose_name='Дата акту виконаних робіт')),
                ('act_value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сума акту виконаних робіт, грн.')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Company', verbose_name='Компанія')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Customer', verbose_name='Замовник')),
            ],
            options={
                'verbose_name': 'Договір',
                'verbose_name_plural': 'Договори',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ПІБ')),
                ('position', models.CharField(max_length=50, verbose_name='Посада')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='Телефон')),
                ('mobile_phone', models.CharField(blank=True, max_length=13, verbose_name='Мобільний телефон')),
                ('avatar', stdimage.models.StdImageField(default='users/avatars/no_image.jpg', upload_to='users/avatars', verbose_name='Фото')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День народження')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Заробітна плата, грн.')),
                ('vacation_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Кількість днів відпустки')),
                ('vacation_date', models.DateField(blank=True, null=True, verbose_name='Дата нарахування відпустки')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Employee', verbose_name='Кервіник')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('date', models.DateField(verbose_name='Дата')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='Дата наступної події')),
                ('repeat', models.CharField(choices=[('OT', 'Одноразова подія'), ('RW', 'Щотижнева подія'), ('RM', 'Щомісячна подія'), ('RY', 'Щорічна подія')], default='OT', max_length=2, verbose_name='Періодичність')),
                ('title', models.CharField(max_length=100, verbose_name='Назва події')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100, verbose_name='Роботи')),
                ('part', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Частка')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Employee', verbose_name='Виконавець')),
            ],
            options={
                'verbose_name': 'Виконавець',
                'verbose_name_plural': 'Виконавці',
            },
        ),
        migrations.CreateModel(
            name='IntTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='Завдання')),
                ('exec_status', models.CharField(choices=[('IW', 'В очікуванні'), ('IP', 'Виконується'), ('HD', 'Виконано')], default='IW', max_length=2, verbose_name='Статус виконання')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Плановий початок робіт')),
                ('planned_finish', models.DateField(blank=True, null=True, verbose_name='Планове закінчення робіт')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='Фактичний початок робіт')),
                ('actual_finish', models.DateField(blank=True, null=True, verbose_name='Фактичне закінчення робіт')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Бонус, грн.')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Employee', verbose_name='Виконавець')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, verbose_name='Назва новини')),
                ('text', models.TextField(verbose_name='Новина')),
                ('news_type', models.CharField(choices=[('OG', 'Організаційні'), ('LS', 'Дозвілля'), ('PR', 'Робочі')], default='PR', max_length=2, verbose_name='Тип новини')),
                ('actual_from', models.DateField(blank=True, null=True, verbose_name='Актуальна з')),
                ('actual_to', models.DateField(blank=True, null=True, verbose_name='Актуальна до')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=30, verbose_name='Назва робіт')),
                ('deal_number', models.CharField(max_length=30, verbose_name='Номер договору')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Вартість робіт, грн.')),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Аванс, грн.')),
                ('pay_status', models.CharField(choices=[('NP', 'Не оплачений'), ('AP', 'Оплачений аванс'), ('PU', 'Оплачений')], default='NP', max_length=2, verbose_name='Статус оплати')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Дата оплати')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Contractor', verbose_name='Підрядник')),
            ],
            options={
                'verbose_name': 'Витрати',
                'verbose_name_plural': 'Витрати',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100, verbose_name='Вид робіт')),
                ('price_code', models.CharField(max_length=8, unique=True, verbose_name='Пункт кошторису')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Вартість робіт, грн.')),
                ('net_price_rate', models.PositiveSmallIntegerField(default=75, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Вартість після вхідних витрат, %')),
                ('owner_bonus', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Бонус керівника проекту, %')),
                ('executors_bonus', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Бонус виконавців, %')),
                ('copies_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Кількість примірників')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Customer', verbose_name='Замовник')),
            ],
            options={
                'verbose_name': 'Вид робіт',
                'verbose_name_plural': 'Види робіт',
                'ordering': ['price_code'],
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Отримувач')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Контактна особа')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Customer', verbose_name='Замовник')),
            ],
            options={
                'verbose_name': 'Адресат',
                'verbose_name_plural': 'Адресати',
            },
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(verbose_name='Дата відправки')),
                ('copies_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Кількість примірників')),
                ('register_num', models.CharField(blank=True, max_length=30, verbose_name='Реєстр')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Коментар')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Receiver', verbose_name='Отримувач проекту')),
            ],
            options={
                'verbose_name': 'Відправка',
                'verbose_name_plural': 'Відправки',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_code', models.CharField(max_length=30, verbose_name='Шифр об’єкту')),
                ('object_address', models.CharField(max_length=255, verbose_name='Адреса об’єкту')),
                ('project_code', models.CharField(blank=True, max_length=30, verbose_name='Шифр проекту')),
                ('exec_status', models.CharField(choices=[('IW', 'В черзі'), ('IP', 'Виконується'), ('HD', 'Виконано')], default='IW', max_length=2, verbose_name='Статус виконання')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='Плановий початок')),
                ('planned_finish', models.DateField(blank=True, null=True, verbose_name='Планове закінчення')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='Фактичний початок')),
                ('actual_finish', models.DateField(blank=True, null=True, verbose_name='Фактичне закінчення')),
                ('tc_received', models.DateField(blank=True, null=True, verbose_name='Дата отримання ТЗ')),
                ('tc_upload', planner.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=planner.models.user_directory_path, verbose_name='Технічне завдання')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('pdf_copy', planner.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=planner.models.user_directory_path, verbose_name='Електронний примірник')),
                ('costs', models.ManyToManyField(blank=True, related_name='tasks', through='planner.Order', to='planner.Contractor', verbose_name='Підрядники')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Deal', verbose_name='Договір')),
                ('executors', models.ManyToManyField(blank=True, related_name='tasks', through='planner.Execution', to='planner.Employee', verbose_name='Виконавці')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Employee', verbose_name='Керівник проекту')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Project', verbose_name='Тип проекту')),
                ('receivers', models.ManyToManyField(through='planner.Sending', to='planner.Receiver', verbose_name='Отримувачі проекту')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
            },
        ),
        migrations.AddField(
            model_name='sending',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Task', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='order',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Task', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='execution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Task', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='project_types',
            field=models.ManyToManyField(blank=True, to='planner.Project', verbose_name='Види робіт'),
        ),
        migrations.AddField(
            model_name='company',
            name='chief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Employee', verbose_name='Керівник'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('object_code', 'project_type', 'deal')},
        ),
        migrations.AlterUniqueTogether(
            name='sending',
            unique_together={('receiver', 'task', 'receipt_date')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('contractor', 'task', 'order_name')},
        ),
        migrations.AlterUniqueTogether(
            name='inttask',
            unique_together={('task_name', 'executor')},
        ),
        migrations.AlterUniqueTogether(
            name='execution',
            unique_together={('executor', 'task', 'part_name')},
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('number', 'customer')},
        ),
    ]
