# Generated by Django 2.0 on 2018-02-12 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата договору'),
        ),
        migrations.AddField(
            model_name='execution',
            name='exec_status',
            field=models.CharField(choices=[('IW', 'В черзі'), ('IP', 'Виконується'), ('HD', 'Виконано')], default='IW', max_length=2, verbose_name='Статус виконання'),
        ),
        migrations.AddField(
            model_name='execution',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата виконання'),
        ),
        migrations.AddField(
            model_name='inttask',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
