# Generated by Django 2.0 on 2018-02-22 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20180212_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
