# Generated by Django 2.0 on 2018-03-05 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0003_execution_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Підрядники', 'verbose_name_plural': 'Підрядник'},
        ),
        migrations.AddField(
            model_name='deal',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='deal_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inttask',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='inttask_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='task_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='planner.Employee', verbose_name='Кервіник'),
            preserve_default=False,
        ),
    ]
