# Generated by Django 2.0.6 on 2018-06-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20180614_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Договір', 'verbose_name_plural': 'Договори'},
        ),
        migrations.AddField(
            model_name='customer',
            name='act_template',
            field=models.CharField(choices=[('gks', 'Шаблон ГКС'), ('msz', 'Шаблон МС')], default='gks', max_length=3, verbose_name='Шаблон акту'),
        ),
    ]
