# Generated by Django 2.0.6 on 2018-06-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20180614_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='taxation',
            field=models.CharField(choices=[('wvat', 'З ПДВ'), ('wovat', 'Без ПДВ')], default='wvat', max_length=5, verbose_name='Система оподаткування'),
        ),
    ]
