# Generated by Django 2.0.6 on 2018-08-09 15:18

from django.db import migrations
import planner.formatChecker
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_company_taxation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-creation_date', 'customer', '-number'], 'verbose_name': 'Договір', 'verbose_name_plural': 'Договори'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-creation_date', '-deal', 'object_code'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекти'},
        ),
        migrations.AddField(
            model_name='deal',
            name='pdf_copy',
            field=planner.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=planner.models.user_directory_path, verbose_name='Електронний примірник'),
        ),
    ]
