# Generated by Django 2.0.6 on 2019-01-26 11:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import planner.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20180809_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['next_date'], 'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created'], 'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=stdimage.models.StdImageField(default='avatars/no_image.jpg', upload_to=planner.models.avatar_directory_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='День народження'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.Employee', verbose_name='Кервіник'),
        ),
    ]
