# Generated by Django 2.2.8 on 2019-12-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_task_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Receiver', verbose_name='Отримувач проекту'),
        ),
    ]
