# Generated by Django 2.2.8 on 2019-12-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_auto_20191023_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='planned_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Планове закінчення'),
        ),
        migrations.AddField(
            model_name='execution',
            name='planned_start',
            field=models.DateField(blank=True, null=True, verbose_name='Плановий початок'),
        ),
    ]
