# Generated by Django 2.2.8 on 2019-12-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_auto_20191205_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='warning',
            field=models.CharField(blank=True, max_length=30, verbose_name='Попередження'),
        ),
    ]
