# Generated by Django 2.2.8 on 2019-12-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_execution_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='ПІБ'),
        ),
    ]
