# Generated by Django 2.2.8 on 2019-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_auto_20191209_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Пункт кошторису'),
        ),
    ]
