# Generated by Django 2.2.8 on 2019-12-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_auto_20191226_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_code',
        ),
    ]
