# Generated by Django 2.2.8 on 2019-12-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_auto_20191226_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project_code',
            field=models.CharField(blank=True, null=True, max_length=30, verbose_name='Шифр проекту'),
        ),
        migrations.RunSQL("UPDATE planner_task SET project_code = NULL WHERE project_code = ''"),
        migrations.AlterField(
            model_name='task',
            name='project_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Шифр проекту'),
        ),
    ]
