# Generated by Django 2.2.10 on 2020-05-06 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_auto_20191226_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='coefficient',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Коєфіцієнт плану'),
        ),
    ]
