# Generated by Django 2.2.8 on 2019-12-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_remove_task_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Шифр проекту'),
        ),
    ]
