# Generated by Django 2.2.10 on 2020-05-07 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_employee_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='coefficient',
            field=models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Коєфіцієнт плану'),
        ),
    ]
