# Generated by Django 2.2.10 on 2020-05-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0025_auto_20200507_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sending_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата відправки'),
        ),
    ]
