# Generated by Django 2.2.10 on 2020-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_task_sending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець виконання'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Початок виконання'),
        ),
    ]
