# Generated by Django 2.2.10 on 2020-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0027_auto_20200524_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['creation_date'], 'verbose_name': 'Виконавець', 'verbose_name_plural': 'Виконавці'},
        ),
        migrations.AlterModelOptions(
            name='inttask',
            options={'ordering': ['-exec_status'], 'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.AlterField(
            model_name='task',
            name='exec_status',
            field=models.CharField(choices=[('IW', 'В черзі'), ('IP', 'Виконується'), ('HD', 'Виконано'), ('ST', 'Надіслано'), ('OH', 'Призупинено'), ('CL', 'Відмінено')], default='IW', max_length=2, verbose_name='Статус виконання'),
        ),
    ]
