# Generated by Django 2.2.10 on 2020-08-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0028_auto_20200805_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inttask',
            options={'ordering': ['-exec_status', '-actual_finish'], 'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
    ]
