# Generated by Django 2.2.10 on 2020-08-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0029_auto_20200819_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
