# Generated by Django 2.2.20 on 2021-04-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0031_auto_20200923_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price_code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Пункт кошторису'),
        ),
    ]
