# Generated by Django 2.2.20 on 2021-07-07 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import planner.formatChecker
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0032_auto_20210429_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата оплати')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сума, грн.')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peyment_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Deal', verbose_name='Договір')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплати',
                'ordering': ['-creation_date', 'deal'],
            },
        ),
        migrations.CreateModel(
            name='ActOfAcceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер акту виконаних робіт')),
                ('date', models.DateField(verbose_name='Дата акту виконаних робіт')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сума акту виконаних робіт, грн.')),
                ('pdf_copy', planner.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=planner.models.user_directory_path, verbose_name='Електронний примірник')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='act_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.Deal', verbose_name='Договір')),
            ],
            options={
                'verbose_name': 'Акт виконаних робіт',
                'verbose_name_plural': 'Акти виконаних робіт',
                'ordering': ['-creation_date', '-number'],
                'unique_together': {('number', 'deal')},
            },
        ),
    ]
