# Generated by Django 2.2.20 on 2021-10-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0035_auto_20210714_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Опис контрагента'),
        ),
        migrations.AddField(
            model_name='company',
            name='regulations',
            field=models.CharField(blank=True, max_length=100, verbose_name='Діє на підставі'),
        ),
        migrations.AddField(
            model_name='company',
            name='signatory_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='Підписант'),
        ),
        migrations.AddField(
            model_name='company',
            name='signatory_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Посада підписанта'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='customer',
            name='legal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Опис контрагента'),
        ),
        migrations.AddField(
            model_name='customer',
            name='regulations',
            field=models.CharField(blank=True, max_length=100, verbose_name='Діє на підставі'),
        ),
        migrations.AddField(
            model_name='customer',
            name='signatory_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='Підписант'),
        ),
        migrations.AddField(
            model_name='customer',
            name='signatory_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Посада підписанта'),
        ),
        migrations.AddField(
            model_name='deal',
            name='parent_deal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата генерального договору'),
        ),
        migrations.AddField(
            model_name='deal',
            name='parent_deal_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер генерального договору'),
        ),
    ]
