# Generated by Django 2.2.20 on 2021-10-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0036_auto_20211020_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Повна назва'),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Повна назва'),
        ),
    ]
