# Generated by Django 2.2.20 on 2021-10-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0037_auto_20211023_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Коефіцієнт складності'),
        ),
    ]
