# Generated by Django 2.2.20 on 2021-11-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0039_task_act_of_acceptance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='difficulty',
            new_name='difficulty_owner',
        ),
    ]
