# Generated by Django 2.2.20 on 2021-11-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0040_auto_20211110_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty_executor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Коефіцієнт виконання'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty_owner',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Коефіцієнт ведення'),
        ),
    ]
