# Generated by Django 2.2.20 on 2021-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0041_auto_20211110_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='signatory_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Посада підписанта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='signatory_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Посада підписанта'),
        ),
    ]
