# Generated by Django 2.2.20 on 2022-01-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0044_payment_act_of_acceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип конструкції')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Тип конструкції',
                'verbose_name_plural': 'Типи конструкцій',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Construction', verbose_name='Тип конструкції'),
        ),
    ]
