# Generated by Django 2.2.20 on 2022-01-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0045_auto_20220104_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='construction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='planner.Construction', verbose_name='Тип конструкції'),
            preserve_default=False,
        ),
    ]
