# Generated by Django 2.2.20 on 2022-01-11 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0046_auto_20220105_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='exec_status',
            field=models.CharField(choices=[('IW', 'В черзі'), ('IP', 'Виконується'), ('HD', 'Виконано'), ('ST', 'Надіслано'), ('CL', 'Відмінено')], default='IW', max_length=2, verbose_name='Статус виконання'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='coefficient',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Коєфіцієнт плану'),
        ),
    ]
