# Generated by Django 2.2.20 on 2022-01-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0047_auto_20220111_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
    ]
