# Generated by Django 2.2.20 on 2022-02-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0048_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
    ]
