# Generated by Django 2.2.20 on 2022-02-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0050_auto_20220210_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['project_type'], 'verbose_name': 'Підзадача', 'verbose_name_plural': 'Підзадачі'},
        ),
        migrations.AlterField(
            model_name='execution',
            name='part_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Роботи'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.SubTask', verbose_name='Підзадача'),
        ),
        migrations.AlterUniqueTogether(
            name='execution',
            unique_together={('executor', 'task', 'subtask')},
        ),
    ]
