# Generated by Django 2.2.20 on 2022-02-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0051_auto_20220211_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.SubTask', verbose_name='Підзадача'),
        ),
    ]
