# Generated by Django 2.2.20 on 2022-02-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0052_order_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Назва робіт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.SubTask', verbose_name='Підзадача'),
        ),
    ]
