# Generated by Django 2.2.20 on 2022-02-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0053_auto_20220212_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['project_type', '-base'], 'verbose_name': 'Підзадача', 'verbose_name_plural': 'Підзадачі'},
        ),
        migrations.AddField(
            model_name='subtask',
            name='add_to_schedule',
            field=models.BooleanField(default=True, verbose_name='Додавати в календар'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.Employee', verbose_name='Виконавець'),
        ),
    ]
