# Generated by Django 2.2.27 on 2022-03-26 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0055_auto_20220318_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='finish_date',
            new_name='actual_finish',
        ),
        migrations.RenameField(
            model_name='execution',
            old_name='start_date',
            new_name='actual_start',
        ),
        migrations.AlterField(
            model_name='employee',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.Employee', verbose_name='Керівник'),
        ),
        migrations.AlterUniqueTogether(
            name='execution',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='execution',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_name',
        ),
    ]
