# Generated by Django 2.2.27 on 2022-04-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0056_auto_20220326_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='head',
        ),
        migrations.AddField(
            model_name='employee',
            name='head',
            field=models.ManyToManyField(blank=True, null=True, related_name='_employee_head_+', to='planner.Employee', verbose_name='Керівники'),
        ),
    ]
