# Generated by Django 2.2.27 on 2022-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0057_auto_20220401_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='head',
            field=models.ManyToManyField(to='planner.Employee', verbose_name='Керівники'),
        ),
    ]
