# Generated by Django 2.2.27 on 2022-04-19 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0059_auto_20220404_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='actual_duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Тривалість виконання'),
        ),
        migrations.AddField(
            model_name='execution',
            name='fixed_date',
            field=models.BooleanField(default=False, verbose_name='Зафіксувати дату'),
        ),
        migrations.AddField(
            model_name='execution',
            name='interruption',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Тривалысть переривання'),
        ),
    ]
