# Generated by Django 2.2.27 on 2022-04-28 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0060_auto_20220419_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='work_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Початок роботи'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='exec_status',
            field=models.CharField(choices=[('IW', 'В черзі'), ('IP', 'Виконується'), ('OH', 'Призупинено'), ('OC', 'На перевірці'), ('HD', 'Виконано')], default='IW', max_length=2, verbose_name='Статус виконання'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='interruption',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Тривалість переривання'),
        ),
    ]
