# Generated by Django 2.2.27 on 2022-04-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0061_auto_20220428_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='simultaneous_execution',
            field=models.BooleanField(default=False, verbose_name='Одночасне виконання'),
        ),
    ]
