# Generated by Django 2.2.27 on 2022-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0062_subtask_simultaneous_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='prev_exec_status',
            field=models.CharField(choices=[('IW', 'В черзі'), ('IP', 'Виконується'), ('OH', 'Призупинено'), ('OC', 'На перевірці'), ('HD', 'Виконано')], default='IW', max_length=2, verbose_name='Попередный статус виконання'),
        ),
    ]
