# Generated by Django 2.2.27 on 2022-04-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0063_execution_prev_exec_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='prev_exec_status',
            field=models.CharField(blank=True, choices=[('IW', 'В черзі'), ('IP', 'Виконується'), ('OH', 'Призупинено'), ('OC', 'На перевірці'), ('HD', 'Виконано')], max_length=2, null=True, verbose_name='Попередный статус виконання'),
        ),
    ]
