# Generated by Django 2.2.27 on 2022-05-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0064_auto_20220430_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='check_required',
            field=models.BooleanField(default=True, verbose_name='Потрібна перевірка'),
        ),
    ]
