# Generated by Django 2.2.27 on 2022-05-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0065_subtask_check_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид будівництва')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Вид будівництва',
                'verbose_name_plural': 'Види будівництва',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.WorkType', verbose_name='Вид будівництва'),
        ),
    ]
