# Generated by Django 2.2.27 on 2022-05-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0066_auto_20220504_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='planner.WorkType', verbose_name='Вид будівництва'),
            preserve_default=False,
        ),
    ]
