# Generated by Django 2.2.27 on 2022-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0067_auto_20220504_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, verbose_name='Номер карти'),
        ),
    ]
