# Generated by Django 2.2.27 on 2022-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0068_employee_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='show_to_customer',
            field=models.BooleanField(default=False, verbose_name='Показувати замовнику'),
        ),
    ]
