# Generated by Django 2.2.27 on 2022-06-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0070_customer_plan_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.DateField(blank=True, null=True, verbose_name='Період проектування'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tc_received',
            field=models.DateField(blank=True, null=True, verbose_name='Отримано ТЗ'),
        ),
    ]
