# Generated by Django 2.2.27 on 2022-07-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0072_remove_task_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='comment',
        ),
    ]
