# Generated by Django 2.2.27 on 2022-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0074_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
    ]
