# Generated by Django 2.2.28 on 2022-10-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0076_remove_deal_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.Construction', verbose_name='Тип конструкції'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.WorkType', verbose_name='Вид будівництва'),
        ),
    ]
