# Generated by Django 2.2.28 on 2022-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0077_auto_20221019_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photo_share',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Папка фото'),
        ),
        migrations.AddField(
            model_name='task',
            name='project_share',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Папка проекту'),
        ),
    ]
