# Generated by Django 3.2.17 on 2023-02-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0078_auto_20221027_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Організаційно-правова форма'),
        ),
        migrations.AddField(
            model_name='customer',
            name='legal_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Організаційно-правова форма'),
        ),
    ]
