# Generated by Django 3.2.17 on 2023-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0079_auto_20230222_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Аванс, грн.'),
        ),
    ]
