# Generated by Django 3.2.18 on 2023-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0080_deal_advance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='pay_status',
            field=models.CharField(choices=[('NP', 'Не оплачений'), ('AP', 'Оплачений аванс'), ('PP', 'Оплачений частково'), ('PU', 'Оплачений')], default='NP', max_length=2, verbose_name='Статус оплати'),
        ),
    ]
