# Generated by Django 3.2.18 on 2023-03-24 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import planner.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0081_alter_deal_pay_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AddField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='order_peyment_approvers', to='auth.user', verbose_name='Погоджено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата погодження'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Коментар'),
        ),
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='order_creators', to='auth.user', verbose_name='Створив'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Призначення'),
        ),
        migrations.AddField(
            model_name='order',
            name='warning',
            field=models.CharField(blank=True, max_length=30, verbose_name='Попередження'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deal_number',
            field=models.CharField(max_length=50, verbose_name='Договір/замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планова дата оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('NP', 'Нове замовлення'), ('AR', 'Погоджена оплата'), ('AP', 'Оплачений аванс'), ('PU', 'Оплачене')], default='NP', max_length=2, verbose_name='Статус оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.subtask', verbose_name='Підзадача'),
        ),
        migrations.AlterField(
            model_name='order',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.task', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата оплати')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сума, грн.')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_peyment_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Оплата замовлення',
                'verbose_name_plural': 'Оплати замовлень',
                'ordering': ['-creation_date', 'order'],
            },
            bases=(planner.mixins.ModelDiffMixin, models.Model),
        ),
    ]
