# Generated by Django 3.2.18 on 2023-03-27 12:38

from django.db import migrations, models
import django.db.models.deletion
import planner.formatChecker
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0081_auto_20230325_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deal',
            field=planner.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=planner.models.user_directory_path, verbose_name='Договір'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('BP', 'По перерахунку'), ('CP', 'Готівка')], default='BP', max_length=2, verbose_name='Статус оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='planner.company', verbose_name='Компанія'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='deal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Договір/замовлення'),
        ),
    ]
