# Generated by Django 3.2.18 on 2023-03-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0082_auto_20230327_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('BV', 'Платіж з ПДВ'), ('BP', 'Платіж без ПДВ'), ('CP', 'Готівка')], default='BV', max_length=2, verbose_name='Форма оплати'),
        ),
    ]
