# Generated by Django 3.2.18 on 2023-03-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0083_alter_order_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accountant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='company_accountant', to='planner.employee', verbose_name='Бухгалтер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='edrpou',
            field=models.CharField(blank=True, max_length=10, verbose_name='ЄДРПОУ'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='edrpou',
            field=models.CharField(blank=True, max_length=10, verbose_name='ЄДРПОУ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='edrpou',
            field=models.CharField(blank=True, max_length=10, verbose_name='ЄДРПОУ'),
        ),
        migrations.AddField(
            model_name='order',
            name='cost_type',
            field=models.CharField(choices=[('PC', 'Проектні затрати'), ('TC', 'Відрядні затрати'), ('OC', 'Канселярські затрати'), ('FA', 'Основні засоби')], default='PC', max_length=2, verbose_name='Стаття затрат'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='doc_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, verbose_name='Призначення платежу'),
        ),
        migrations.AddField(
            model_name='payment',
            name='doc_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, verbose_name='Призначення платежу'),
        ),
        migrations.AlterField(
            model_name='company',
            name='chief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_chiefs', to='planner.employee', verbose_name='Керівник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deal_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Договір/замовлення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Призначення'),
            preserve_default=False,
        ),
    ]
