# Generated by Django 3.2.18 on 2023-03-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0084_auto_20230330_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенти'},
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='Контактна особа'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Телефон'),
        ),
    ]
