# Generated by Django 3.2.18 on 2023-03-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0085_auto_20230330_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('NP', 'Нове замовлення'), ('AR', 'Погоджена оплата'), ('AP', 'Погоджений аванс'), ('AP', 'Оплачений аванс'), ('PU', 'Оплачене')], default='NP', max_length=2, verbose_name='Статус оплати'),
        ),
    ]
