# Generated by Django 3.2.18 on 2023-04-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0086_alter_order_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost_type',
            field=models.CharField(choices=[('PC', 'Проектні витрати'), ('TC', 'Відрядні витрати'), ('OC', 'Офісні витрати'), ('CC', 'Канцелярські витрати'), ('FA', 'Основні засоби'), ('UP', 'Комунальні платежі'), ('LC', 'Оплата праці'), ('TA', 'Податки')], default='PC', max_length=2, verbose_name='Стаття затрат'),
        ),
    ]
