# Generated by Django 3.2.18 on 2023-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0087_alter_order_cost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('NP', 'Нове замовлення'), ('AR', 'Погоджена оплата'), ('AA', 'Погоджений аванс'), ('AP', 'Оплачений аванс'), ('PU', 'Оплачене')], default='NP', max_length=2, verbose_name='Статус оплати'),
        ),
    ]
