# Generated by Django 3.2.18 on 2023-04-27 17:25

from django.db import migrations, models
import django.db.models.deletion
import planner.formatChecker
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0089_auto_20230418_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pdf_copy',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер рахунку')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата рахунку')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сума, грн.')),
                ('pdf_copy', planner.formatChecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=planner.models.user_directory_path, verbose_name='Рахунок')),
                ('act_of_acceptance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.actofacceptance', verbose_name='Акт виконаних робіт')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.deal', verbose_name='Договір')),
            ],
            options={
                'verbose_name': 'Рахунок',
                'verbose_name_plural': 'Рахунки',
                'ordering': ['-invoice_date', 'deal'],
            },
        ),
    ]
