# Generated by Django 3.2.18 on 2023-06-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0092_construction_name_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='linked',
            field=models.BooleanField(default=False, verbose_name='Розпізнаний'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.company', verbose_name='Платник'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.contractor', verbose_name='Отримувач'),
        ),
        migrations.AddField(
            model_name='payment',
            name='linked',
            field=models.BooleanField(default=False, verbose_name='Розпізнаний'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.customer', verbose_name='Платник'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.company', verbose_name='Отримувач'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.deal', verbose_name='Договір'),
        ),
        migrations.CreateModel(
            name='IgnoreEDRPOU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edrpou', models.CharField(blank=True, max_length=10, verbose_name='ЄДРПОУ')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опис')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.company', verbose_name='Компанія')),
            ],
            options={
                'verbose_name': 'Ігнорувати ЄДРПОУ',
                'verbose_name_plural': 'Ігнорувати ЄДРПОУ',
                'ordering': ['description'],
                'unique_together': {('company', 'edrpou')},
            },
        ),
    ]
