# Generated by Django 3.2.18 on 2023-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0093_auto_20230622_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='difficulty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Коефіцієнт складності'),
        ),
    ]
