# Generated by Django 3.2.18 on 2023-07-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0095_auto_20230703_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='difficulty',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=3, verbose_name='Коефіцієнт складності'),
        ),
    ]
