# Generated by Django 3.2.18 on 2023-07-14 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0097_subtask_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_start', models.DateField(verbose_name='Початкова дата')),
                ('plan_finish', models.DateField(verbose_name='Кінцева дата')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_creators', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('tasks', models.ManyToManyField(blank=True, to='planner.Execution', verbose_name='Задачі')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Плани',
                'ordering': ['-creation_date'],
            },
        ),
    ]
