# Generated by Django 3.2.18 on 2023-08-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0099_auto_20230714_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='planner.employee', verbose_name='Керівник'),
            preserve_default=False,
        ),
    ]
