# Generated by Django 3.2.18 on 2023-10-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0100_plan_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exclude_costs',
            field=models.BooleanField(default=False, verbose_name='Виключати витрати'),
        ),
    ]
